---
title: "HomeR"
author: "Maseeng"
date: "12/10/2020"
output: html_document
---

```{r, eval = FALSE}
install.packages("adehabitatHR")
install.packages("rgdal")
install.packages("raster")
install.packages("rgeos")
install.packages("maptools")
install.packages("lubridate")
install.packages("sp")
install.packages("lunar")
install.packages("BBMM")
install.packages("oce")
install.packages("rhr")
install.packages("RHRV")
#If you have previously installed these packages, load the libraries:

```

```{r, eval = FALSE}

ROADS <- readOGR(dsn="D:/Work_folder/CPED Turtle data for EMC Intern", layer="roads", stringsAsFactors = F)
ROADS


summary(ROADS@data)

TURTLEPOINTS <- readOGR(dsn="D:/Work_folder/CPED Turtle data for EMC Intern", layer="TECA_1998_1999_TurtlePoints", stringsAsFactors = F)
TURTLEPOINTS

summary(TURTLEPOINTS@data)

TURTLEPOINTS02 <- readOGR(dsn="D:/Work_folder/CPED Turtle data for EMC Intern", layer="TECA_Studies_TurtlePoints_2000_2004", stringsAsFactors = F)
TURTLEPOINTS02


summary(TURTLEPOINTS02@data)

```


```{r, eval = FALSE}




```