---
title: "Trial 02"
author: "Maseeng"
date: "12/15/2020"
output: html_document
---

```{r setup, include=FALSE}

usePackage	<- function(p)	
{
		if	(!is.element(p,	installed.packages()[,1]))
				install.packages(p,	dep	= TRUE)
		require(p,	character.only	= TRUE)
}
pkg<-c("sp","lubridate",	"rgdal",	"maptools",		"adehabitatHR",	"rgdal",	"rast
er",	"BBMM",	"lunar",	"oce",	"move")
lapply(pkg,	usePackage)
lapply(pkg,	library,	character.only=TRUE)
install.packages("rhr",	repos=c("http://78.47.85.98/R",		
																																"http://cran.rstudio.com/"),	dep	= TRUE)
library(rhr)

```


```{r, eval=FALSE}
input	= "D:/Work_folder/CPED Turtle data for EMC Intern"
x	= "Longitude" #	The	column	name	of	your	x	coordinate
y	= "Latitude" #	The	column	name	of	your	y	coordinate
datetime.code	= "dmy_HMS" #modify	this	using	documentation	in	Lubridate
Datecolumn= "GMT.Date"
Timecolumn= "GMT.Time"
timezone	= "UTC"
input.projection	= "+init=epsg:4326"
na.operator = "N/A"

```

```{r, eval = FALSE}

#	Load	required	packages
require(sp)
require(lubridate)

```

```{r, eval = FALSE}
setwd(input)
datalist	<- list()	
files	<- list.files(input)
files

```


```{r, eval = FALSE}

for(file	in	files)	{
		stem	<-gsub("\\.csv$","",file)
		datalist[[stem]]	<- (read.csv(file, stringsAsFactors=FALSE, na.strings=na.operator))
}

```


```{r, eval = FALSE}

#	Read	in	CSV	files.	
for(file	in	files)	{
		stem	<-gsub("\\.csv$","",file)
		datalist[[stem]]	<- (read.csv(file,	stringsAsFactors=FALSE,	na.strings=na.operator))
}

```


```{r, eval = FALSE}

#	Loop	through	csv	files	and	create	a	list	of	SpatialPointsDataFrames
newlist<-list()
#for	loop	for	going	through	each	file		
for	(i	in	1:length(datalist)){
		infile	= datalist[[i]]
		infile	= subset(infile,	infile[,x]!="NA")
		infile	= subset(infile,	infile[,y]!="NA")
		Date	= infile[,Datecolumn]
		Time	= infile[,Timecolumn]
		infile$Date.Time<-parse_date_time(paste(Date,	Time),
		                                  datetime.code,	
		tz=timezone)
		xy	= infile[,c(x,	y)]
    coordinates(xy)<-c(x,y)
		proj4string(xy)<-CRS(input.projection)
		infile2<-SpatialPointsDataFrame(xy,	infile)
		name	= names(datalist[i])
		newlist[[i]]<-infile2
		names(newlist)[i]<-name
}
rm(Date,	file,	files,	i,	infile2,	name,	Time,	xy,	Datecolumn,	input, pkg,	stem,	Timecolumn,	timezone,usePackage)	#	remove	unwanted	objects

```

```{r, eval = False}



```